###########SENSORS#################
CREATE DATABASE IF NOT EXISTS SafeHomeIoTEvents;
USE SafeHomeIoTEvents;

DROP TABLE IF EXISTS temperatureMessage;
CREATE TABLE temperatureMessage (
	ID INT AUTO_INCREMENT, 
	deviceID INT,
	measurement FLOAT,
	type VARCHAR(30),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	userID INT,
	PRIMARY KEY(ID)
);

CREATE TABLE imageMessage (
	ID INT AUTO_INCREMENT, 
	deviceID INT,
	description VARCHAR(30),
	type VARCHAR(30),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	userID INT,
	PRIMARY KEY(ID)
);

CREATE TABLE videoMessage (
	ID INT AUTO_INCREMENT, 
	deviceID INT,
	description VARCHAR(30),
	type VARCHAR(30),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	userID INT,
	PRIMARY KEY(ID)
);

CREATE TABLE smokeMessage (
	ID INT AUTO_INCREMENT, 
	deviceID INT,
	measurement FLOAT,
	type VARCHAR(30),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	userID INT,
	PRIMARY KEY(ID)
);


CREATE TABLE motionMessage (
	ID INT AUTO_INCREMENT, 
	deviceID INT,
	description VARCHAR(30),
	type VARCHAR(30),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	userID INT,
	PRIMARY KEY(ID)
);



CREATE TABLE device(ID INT AUTO_INCREMENT, userID INT, deviceType VARCHAR(20), PRIMARY KEY(ID));

CREATE TABLE deviceConfiguration(ID INT AUTO_INCREMENT, userID INT, PRIMARY KEY(ID,userID), description VARCHAR(200));

